# pytorch张量

## 1-1pytorch张量与数据类型

Tensor(张量)  
- 构造一个随机初始化的矩阵:torch.rand
- 全0矩阵:torch.zeros
- 全1矩阵:torch.ones
- 直接从数据构造张量:torch.tensor

### 创建张量

In [1]:
import torch

#### 创建指定符合正态分布的张量

In [2]:
X = torch.rand(2,3) #创建两行三列的矩阵，正态分布的随机数 

In [3]:
X

tensor([[0.9080, 0.5990, 0.9454],
        [0.8307, 0.9805, 0.5999]])

#### 创建指定维数0张量 

In [4]:
X1 = torch.zeros(3,4) #生成3行4列的数组  
X1 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### 创建指定维数的1张量

In [5]:
X2 = torch.ones(4,4)
X2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

.size可以轻松的返回指定的维度的大小,但是用shape的话就需要切片了

In [6]:
X2.size() 

torch.Size([4, 4])

In [8]:
X2.shape

torch.Size([4, 4])

In [9]:
X2.size(0)

4

In [11]:
X2.shape[0] 

4

### tensor的基本数据类型

- 32位浮点型 torch.float32
- 64位浮点型 torch.float64
- 32位整型 torch.int32
- 16位整形 torch.int16
- 64位整形 torch.int64 

### 数据类型的转换 

#### 从列表创建一个tensor

##### 创建的时候可以指定dtype

In [12]:
x0 = torch.tensor([6,2],dtype=torch.float32)
x0

tensor([6., 2.])

In [13]:
x0.type() 

'torch.FloatTensor'

##### 数据类型的转化

In [ ]:
x0.type(torch.int64)

也可以在创建的时候就指定

In [14]:
x1 = torch.ones((3,3),dtype = torch.int32)
x1

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

#### tensor与ndarry类型的转换

In [15]:
import numpy as np 

In [16]:
a = np.random.randn(2,3)

In [17]:
a

array([[ 0.06564994, -0.78885034,  0.76846734],
       [-0.17964152, -0.7552049 ,  0.89089908]])

#### 从numpy创建张量（将ndarry转换成tensor） 

In [18]:
x2 = torch.from_numpy(a)
x2

tensor([[ 0.0656, -0.7889,  0.7685],
        [-0.1796, -0.7552,  0.8909]], dtype=torch.float64)

#### 将tensor转换成ndarry

In [19]:
n = x2.numpy()
n

array([[ 0.06564994, -0.78885034,  0.76846734],
       [-0.17964152, -0.7552049 ,  0.89089908]])